const ESTADOS = {
  PENDIENTE: "PENDIENTE",
  TOMADO: "TOMADO",
  PROCESANDO: "PROCESANDO",
  OK: "OK",
  OK_PARCIAL: "OK_PARCIAL",
  ERROR: "ERROR",
  REINTENTO_PENDIENTE: "REINTENTO_PENDIENTE"
};

const WORKER_TIPO = {
  OPERATIVO: "OPERATIVO",
  SYNC: "SYNC"
};

const JOBS_OPERATIVOS = new Set([
  "VALIDAR_USUARIO",
  "CREAR_USUARIO",
  "CAMBIAR_CLAVE",
  "CARGA_MANUAL",
  "CARGAR_FICHAS",
  "PROCESAR_CARGA",
  "CARGA_LANDING_APROBADA",
  "RETIRO_MANUAL",
  "RETIRO",
  "PROCESAR_RETIRO",
  "RETIRO_LANDING_APROBADO"
]);

const JOBS_SYNC = new Set([
  "REGISTRAR_CHUNIOR",
  "SYNC_SALDO_BILLETERA",
  "CONTROL_RETIRO_24H",
  "ACTUALIZAR_HISTORIAL",
  "CONCILIACION_GENERAL",
  "SYNC_MASIVO_BILLETERAS"
]);

module.exports = { ESTADOS, WORKER_TIPO, JOBS_OPERATIVOS, JOBS_SYNC };
